version: '3.8'

services:
  frontend:
    container_name: rfx-audit-v4
    build:
      context: .
      args:
        - VITE_SUPABASE_URL
        - VITE_SUPABASE_ANON_KEY
        - VITE_STRIPE_PUBLISHABLE_KEY
    restart: always
    ports:
      - "3002:80"  # External port → internal nginx static server
    networks:
      - core-services_stack_proxy-tier

networks:
  core-services_stack_proxy-tier:
    external: true
